name: piktid-assignment

services:
  frontend:
    image: piktid-swap-frontend
    container_name: frontend
    build: frontend
    restart: always
    ports:
      - ${WEBAPP_HTTP_PORT:-80}:80
      - ${WEBAPP_HTTPS_PORT:-443}:443
    environment:
      BASE_API_URL: ${PIKTID_BASE_API_URL}
      GOOGLE_CLIENT_ID: ${PIKTID_GOOGLE_CLIENT_ID}
      GOOGLE_LOGIN_SECRET_KEY: ${PIKTID_GOOGLE_LOGIN_SECRET_KEY}
    depends_on:
      - queue-manager

  queue-manager:
    image: piktid-queue-manager
    container_name: queue-manager
    build: queue-manager
    restart: always
    environment:
      BASE_API_URL: ${PIKTID_BASE_API_URL}
